name: flutter_app_pic
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  photo_manager: ^0.3.3
#  zoomable_image: ^1.3.1
  cool_ui: ^0.1.14
  camera: ^0.4.3+2
  path_provider: ^0.5.0+1
  image_picker_saver: ^0.1.0
  video_player: ^0.10.0+5
  lamp: ^0.0.6
  photo_view: ^0.3.1
  shared_preferences : ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_colorpicker:
    path: vendor/flutter_colorpicker-0.2.3

  zoomable_image:
    path: vendor/zoomable_image-1.3.1
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
  - assets/images/img_camera_bg@2x.png
  - assets/images/btn_camera_album@2x.png
  - assets/images/btn_camera_camera@2x.png
  - assets/images/icon_index_copy@2x.png
  - assets/images/poppup_bg@2x.png

  - assets/images/icon_index_voice_on@2x.png
  - assets/images/icon_index_voice_off@2x.png
  - assets/images/icon_index_minute_adjust@2x.png

  - assets/images/icon_bottom_color@2x.png
  - assets/images/icon_bottom_height@2x.png
  - assets/images/icon_bottom_width@2x.png
  - assets/images/icon_bottom_adaptation@2x.png
  - assets/images/icon_bottom_rotate_l_r@2x.png
  - assets/images/icon_bottom_rotate_rotate_90@2x.png
  - assets/images/icon_bottom_center_alignment@2x.png
  - assets/images/btn_camera_photo_normal@2x.png
  - assets/images/btn_camera_video_normal@2x.png
  - assets/images/icon_camera_change@2x.png
  - assets/images/btn_camera_video_press@2x.png
  - assets/images/btn_camera_video_press@2x.png
  - assets/images/icon_flash_off@2x.png
  - assets/images/icon_flash_auto@2x.png

  - assets/images/img_pic_bg_01@2x.png
  - assets/images/img_pic_bg_02@2x.png
  - assets/images/img_pic_bg_03@2x.png
  - assets/images/img_pic_bg_04@2x.png
  - assets/images/img_pic_bg_05@2x.png
  - assets/images/img_pic_bg_06@2x.png
  - assets/images/img_pic_bg_07@2x.png
  - assets/images/img_pic_bg_08@2x.png
  - assets/images/img_pic_bg_09@2x.png
  - assets/images/img_pic_bg_10@2x.png
  - assets/images/img_pic_bg_11@2x.png
  - assets/images/img_pic_bg_12@2x.png
  - assets/images/img_pic_bg_13@2x.png
  - assets/images/img_pic_bg_14@2x.png
  - assets/images/img_pic_bg_15@2x.png
  - assets/images/img_pic_bg_16@2x.png
  - assets/images/img_pic_bg_17@2x.png
  - assets/images/img_pic_bg_18@2x.png
  - assets/images/img_pic_bg_19@2x.png
  - assets/images/img_pic_bg_20@2x.png
  - assets/images/img_pic_bg_21@2x.png


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
